// Code generated by the multiversx-sc proxy generator. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![allow(dead_code)]
#![allow(clippy::all)]

use multiversx_sc::proxy_imports::*;

pub struct ChainBallotXProxy;

impl<Env, From, To, Gas> TxProxyTrait<Env, From, To, Gas> for ChainBallotXProxy
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    type TxProxyMethods = ChainBallotXProxyMethods<Env, From, To, Gas>;

    fn proxy_methods(self, tx: Tx<Env, From, To, (), Gas, (), ()>) -> Self::TxProxyMethods {
        ChainBallotXProxyMethods { wrapped_tx: tx }
    }
}

pub struct ChainBallotXProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    wrapped_tx: Tx<Env, From, To, (), Gas, (), ()>,
}

#[rustfmt::skip]
impl<Env, From, Gas> ChainBallotXProxyMethods<Env, From, (), Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    Gas: TxGas<Env>,
{
    pub fn init(
        self,
    ) -> TxTypedDeploy<Env, From, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_deploy()
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> ChainBallotXProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn pause(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("pause")
            .original_result()
    }

    pub fn unpause(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("unpause")
            .original_result()
    }

    pub fn transfer_ownership<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        new_owner: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("transfer_ownership")
            .argument(&new_owner)
            .original_result()
    }

    pub fn create_proposal<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg2: ProxyArg<u64>,
    >(
        self,
        title: Arg0,
        description: Arg1,
        duration: Arg2,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("create_proposal")
            .argument(&title)
            .argument(&description)
            .argument(&duration)
            .original_result()
    }

    pub fn vote<
        Arg0: ProxyArg<u64>,
    >(
        self,
        proposal_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("vote")
            .argument(&proposal_id)
            .original_result()
    }

    pub fn cancel_proposal<
        Arg0: ProxyArg<u64>,
    >(
        self,
        proposal_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("cancel_proposal")
            .argument(&proposal_id)
            .original_result()
    }

    pub fn get_proposal_title<
        Arg0: ProxyArg<u64>,
    >(
        self,
        proposal_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedBuffer<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("get_proposal_title")
            .argument(&proposal_id)
            .original_result()
    }

    pub fn get_proposal_description<
        Arg0: ProxyArg<u64>,
    >(
        self,
        proposal_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedBuffer<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("get_proposal_description")
            .argument(&proposal_id)
            .original_result()
    }

    pub fn get_proposal_creator<
        Arg0: ProxyArg<u64>,
    >(
        self,
        proposal_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedAddress<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("get_proposal_creator")
            .argument(&proposal_id)
            .original_result()
    }

    pub fn get_proposal_vote_count<
        Arg0: ProxyArg<u64>,
    >(
        self,
        proposal_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, u64> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("get_proposal_vote_count")
            .argument(&proposal_id)
            .original_result()
    }

    pub fn get_proposal_deadline<
        Arg0: ProxyArg<u64>,
    >(
        self,
        proposal_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, u64> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("get_proposal_deadline")
            .argument(&proposal_id)
            .original_result()
    }

    pub fn is_proposal_active<
        Arg0: ProxyArg<u64>,
    >(
        self,
        proposal_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, bool> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("is_proposal_active")
            .argument(&proposal_id)
            .original_result()
    }

    pub fn get_total_proposals(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, u64> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("get_total_proposals")
            .original_result()
    }

    pub fn get_total_votes(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, u64> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("get_total_votes")
            .original_result()
    }

    pub fn has_user_voted_on_proposal<
        Arg0: ProxyArg<u64>,
        Arg1: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        proposal_id: Arg0,
        user_address: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, bool> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("has_user_voted_on_proposal")
            .argument(&proposal_id)
            .argument(&user_address)
            .original_result()
    }

    pub fn is_contract_paused(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, bool> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("is_contract_paused")
            .original_result()
    }

    pub fn get_owner(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedAddress<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("get_owner")
            .original_result()
    }
}
