// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           17
// Async Callback (empty):               1
// Total number of exported functions:  19

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    chainballotx
    (
        init => init
        pause => pause
        unpause => unpause
        transfer_ownership => transfer_ownership
        create_proposal => create_proposal
        vote => vote
        cancel_proposal => cancel_proposal
        get_proposal_title => get_proposal_title
        get_proposal_description => get_proposal_description
        get_proposal_creator => get_proposal_creator
        get_proposal_vote_count => get_proposal_vote_count
        get_proposal_deadline => get_proposal_deadline
        is_proposal_active => is_proposal_active
        get_total_proposals => get_total_proposals
        get_total_votes => get_total_votes
        has_user_voted_on_proposal => has_user_voted_on_proposal
        is_contract_paused => is_contract_paused
        get_owner => get_owner
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
